[program:thematch_bot]
directory=/path/to/your/bot
command=python3 bot.py
autostart=true
autorestart=true
stderr_logfile=/var/log/thematch_bot/err.log
stdout_logfile=/var/log/thematch_bot/out.log
stopasgroup=true
killasgroup=true
startsecs=10
startretries=10
priority=1000